### ISSUE TITLE
Live demo please

### ISSUE THREAD

**Issue by luckylooke** [hollowdoor/dom_autoscroller#3]
Is there a live demo somewhere, so I can see it in action quickly? Thanks

**Comment by hollowdoor** [comment]
I think this is a good idea. I'll try to make a github page soon. I have some other functionality I want to add to pointer-point first which is the base of dom-autorscroller. So that will take a little bit of time. Once that's done I'll start on the github page.

For now you'll have to use the README docs as is. I haven't placed a live demo anywhere yet, and I'm pretty sure no one else has made one either.

What's your opinion of the README for this repo? While were at it I'll improve that too if you have any criticisms.

**Comment by luckylooke** [comment]
Readme is fine.. but for people like me who wants to quick try it is
uncomfortable to copy pasting code somewhere. You could make a codepen or
jsfiddle while gh-pages are not ready yet ;)

**Comment by hollowdoor** [comment]
Haha ok. I'll have a demo ready hopefully today.

**Comment by hollowdoor** [comment]
Here is a fiddle.

[dom-autoscroller Demo](https://jsfiddle.net/hollowdoor/a2or8sez/)

It's not all that pretty right now, but it gets the point across.

I appreciate the suggestion. A demo will also give people something to test if they want to contribute issues before they install it.

**Comment by luckylooke** [comment]
Perfect! All I needed ;) :star2:
